"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Badge, Button, DataQualityBadge, EmptyState, Panel, PanelHeader, SectionHeader } from "@/components/ui";
import { PROVIDER_CATALOG, providerCatalogEntry, type ProviderCategory } from "@/lib/provider-management-api";

const categories: { id: ProviderCategory | "all"; label: string }[] = [{ id: "all", label: "All providers" }, { id: "cloud", label: "Cloud" }, { id: "local", label: "Local" }, { id: "custom", label: "Custom" }];

export function ProviderList() {
  const [category, setCategory] = useState<ProviderCategory | "all">("all");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [selected, setSelected] = useState("openrouter");
  const visible = useMemo(() => category === "all" ? PROVIDER_CATALOG : PROVIDER_CATALOG.filter((provider) => provider.category === category), [category]);

  return <div className="space-y-5"><SectionHeader eyebrow="SETTINGS / AI PROVIDERS" title="AI providers" description="Connect the model providers Agnostix can use for research, evaluation, and agents." actions={<Button onClick={() => setDialogOpen(true)}>Add provider</Button>} /><Panel><div className="flex gap-1 overflow-x-auto border-b border-border px-3 pt-2">{categories.map((item) => <button key={item.id} type="button" onClick={() => setCategory(item.id)} className={`border-b-2 px-3 py-2 text-xs transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${category === item.id ? "border-accent text-foreground" : "border-transparent text-muted hover:text-foreground"}`}>{item.label}</button>)}</div><div className="divide-y divide-border/50">{visible.map((provider) => <ProviderRow key={provider.id} provider={provider} />)}</div>{visible.length === 0 ? <EmptyState title="No providers in this category" description="Choose another category or add a provider when the backend integration is available." /> : null}</Panel><Panel><PanelHeader title="Credential boundary" /><p className="px-4 py-3 text-xs leading-relaxed text-muted">Credential storage backend integration is pending. This UI never persists API keys in browser storage or retrieves them after save.</p></Panel>{dialogOpen ? <AddProviderDialog selected={selected} onSelect={setSelected} onClose={() => setDialogOpen(false)} /> : null}</div>;
}

function ProviderRow({ provider }: { provider: typeof PROVIDER_CATALOG[number] }) {
  return <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-4 transition-colors hover:bg-elevated/30"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded border border-border bg-elevated font-mono text-sm text-accent">{provider.name.slice(0, 1)}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/settings/providers/${provider.id}`} className="text-sm font-medium text-foreground hover:text-accent">{provider.name}</Link><Badge>{provider.category}</Badge><DataQualityBadge state="unavailable" /></div><p className="mt-1 text-xs text-muted">{provider.description}</p></div></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-2xs text-subtle">Models / default</p><p className="mt-1 font-mono text-xs text-muted">— / —</p></div><Link href={`/settings/providers/${provider.id}`} className="rounded border border-border px-2.5 py-1.5 text-2xs text-muted hover:border-border-strong hover:text-foreground">Manage</Link></div></div>;
}

function AddProviderDialog({ selected, onSelect, onClose }: { selected: string; onSelect: (id: string) => void; onClose: () => void }) {
  const provider = providerCatalogEntry(selected);
  return <div className="fixed inset-0 z-30 flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="add-provider-title" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-md border border-border-strong bg-surface shadow-2xl shadow-black/50 sm:rounded-md"><div className="flex items-start justify-between border-b border-border px-4 py-4"><div><p className="text-2xs uppercase tracking-[0.18em] text-accent">Provider setup</p><h2 id="add-provider-title" className="mt-1 text-base font-semibold text-foreground">Add AI provider</h2><p className="mt-1 text-xs text-muted">Select a provider and prepare its connection details.</p></div><button type="button" aria-label="Close add provider dialog" onClick={onClose} className="text-sm text-subtle hover:text-foreground">ESC</button></div><div className="grid gap-4 p-4 md:grid-cols-[220px_1fr]"><div className="space-y-1"><p className="mb-2 text-2xs uppercase tracking-wider text-subtle">Provider</p>{PROVIDER_CATALOG.map((item) => <button key={item.id} type="button" onClick={() => onSelect(item.id)} className={`flex w-full items-center justify-between rounded border px-2.5 py-2 text-left text-xs ${selected === item.id ? "border-accent/60 bg-accent/10 text-foreground" : "border-transparent text-muted hover:border-border hover:bg-elevated"}`}><span>{item.name}</span><span className="text-2xs text-subtle">{item.category}</span></button>)}</div><ProviderForm provider={provider} /></div></section></div>;
}

function ProviderForm({ provider }: { provider: typeof PROVIDER_CATALOG[number] }) {
  return <div className="space-y-4"><div className="rounded border border-warning/30 bg-warning/5 px-3 py-2 text-xs text-warning">Backend integration pending. Form values remain in memory and cannot be saved yet.</div><fieldset className="space-y-3"><legend className="text-2xs uppercase tracking-wider text-subtle">Connection</legend><label className="block text-xs text-muted">Base URL<input type="url" placeholder={provider.id === "ollama" ? "http://localhost:11434" : "https://provider.example.com/v1"} className="mt-1 h-9 w-full rounded border border-border bg-elevated px-2.5 text-xs text-foreground outline-none placeholder:text-subtle focus:border-accent focus:ring-1 focus:ring-accent" /></label>{provider.id !== "ollama" ? <label className="block text-xs text-muted">API key<input type="password" autoComplete="new-password" placeholder="Enter key for future backend save" className="mt-1 h-9 w-full rounded border border-border bg-elevated px-2.5 text-xs text-foreground outline-none placeholder:text-subtle focus:border-accent focus:ring-1 focus:ring-accent" /></label> : null}<label className="block text-xs text-muted">Default model<input type="text" placeholder="provider/model" className="mt-1 h-9 w-full rounded border border-border bg-elevated px-2.5 text-xs text-foreground outline-none placeholder:text-subtle focus:border-accent focus:ring-1 focus:ring-accent" /></label></fieldset><div className="flex flex-wrap justify-end gap-2 border-t border-border pt-4"><Button variant="ghost">Test connection · pending</Button><Button disabled>Save provider</Button></div></div>;
}
