"use client";

import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getAgentEvents } from "@/lib/api";
import { getSnapshot } from "@/lib/markets-api";
import { getEvidence, getFundamentals, getLatestResearch, getResearchDocuments, getResearchHistory, postRunResearch, type Assessment, type EvidenceRef, type Thesis } from "@/lib/research-api";
import { Badge, DataQualityBadge, EmptyState, ErrorState, EvidenceItem, LoadingState, ModelBadge, Panel, PanelHeader, SectionHeader } from "@/components/ui";

const VIEW_STYLES: Record<string, string> = { BULLISH: "text-positive", BEARISH: "text-negative", NEUTRAL: "text-muted", INSUFFICIENT_DATA: "text-warning" };
const VERDICT_STYLES: Record<string, string> = { PASS: "text-positive", REVISE: "text-warning", REJECT: "text-negative" };
const METRIC_LABELS: Record<string, string> = { revenue: "Revenue", revenue_growth: "Revenue growth", gross_profit: "Gross profit", gross_margin: "Gross margin", operating_income: "Operating income", operating_margin: "Operating margin", net_income: "Net income", net_margin: "Net margin", eps: "EPS", free_cash_flow: "Free cash flow", total_debt: "Total debt", cash_and_equivalents: "Cash" };

export default function ResearchSymbolPage({ params }: { params: { symbol: string } }) {
  const symbol = params.symbol.toUpperCase();
  const qc = useQueryClient();
  const research = useQuery({ queryKey: ["research", symbol], queryFn: () => getLatestResearch(symbol), retry: false });
  const snapshot = useQuery({ queryKey: ["snapshot", symbol], queryFn: () => getSnapshot(symbol), retry: false });
  const fundamentals = useQuery({ queryKey: ["fundamentals", symbol], queryFn: () => getFundamentals(symbol) });
  const evidence = useQuery({ queryKey: ["evidence", symbol], queryFn: () => getEvidence(symbol), retry: false });
  const documents = useQuery({ queryKey: ["documents", symbol], queryFn: () => getResearchDocuments(symbol), retry: false });
  const history = useQuery({ queryKey: ["research-history", symbol], queryFn: () => getResearchHistory(symbol) });
  const events = useQuery({ queryKey: ["agent-events", 100], queryFn: () => getAgentEvents(100) });
  const run = useMutation({ mutationFn: () => postRunResearch(symbol), onSuccess: () => { qc.invalidateQueries({ queryKey: ["research", symbol] }); qc.invalidateQueries({ queryKey: ["research-history", symbol] }); qc.invalidateQueries({ queryKey: ["agent-events", 100] }); } });

  const thesis: Thesis | null = research.data?.research_output ?? null;
  const critic = research.data?.critic_output ?? null;
  const market = snapshot.data?.market ?? {};
  const security = asRecord(market.security);
  const bar = asRecord(market.latest_bar);
  const quote = asRecord(market.quote);
  const price = numberValue(bar?.close) ?? numberValue(quote?.last_price);
  const runEvents = Array.isArray(events.data) ? events.data.filter((event) => event.payload.run_id === research.data?.id || event.payload.run_id === String(research.data?.id)) : [];
  const evidenceItems = evidence.data?.length ? evidence.data : thesis?.evidence ?? [];

  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><Link href="/research" className="text-xs text-muted hover:text-foreground">Research /</Link><span className="font-mono text-2xl font-semibold tracking-tight text-foreground">{symbol}</span><DataQualityBadge state={overallQuality(snapshot.data?.data_quality)} /></div><p className="mt-1 text-sm text-muted">{typeof security?.name === "string" ? security.name : "Company name unavailable"}{typeof security?.exchange === "string" ? ` · ${security.exchange}` : ""}</p></div><div className="flex items-center gap-2"><button onClick={() => run.mutate()} disabled={run.isPending} className="rounded border border-accent/50 bg-accent/10 px-3 py-2 text-xs text-accent transition-colors hover:bg-accent/20 disabled:opacity-50">{run.isPending ? "running…" : "run research"}</button></div></div>
    <Panel><div className="grid gap-4 px-4 py-3 sm:grid-cols-4"><MarketValue label="Latest price" value={price != null ? price.toFixed(2) : "—"} /><MarketValue label="Market freshness" value={qualityLabel(snapshot.data?.data_quality, "bars")} /><MarketValue label="Research status" value={research.data?.status ?? (research.isLoading ? "loading…" : "not available")} /><MarketValue label="Last completed" value={research.data?.completed_at ? new Date(research.data.completed_at).toLocaleString() : "—"} /></div></Panel>
    {run.isError ? <p role="alert" className="text-xs text-negative">Research run failed: {(run.error as Error)?.message ?? "unknown error"}</p> : null}
    {research.isLoading ? <Panel><LoadingState label={`Loading research for ${symbol}…`} /></Panel> : research.isError ? <Panel><EmptyState title="No completed research" description={`There is no completed research run for ${symbol}. Start a run when the backend is configured.`} /></Panel> : null}
    {thesis ? <>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1.65fr)_minmax(280px,0.85fr)]"><Panel><PanelHeader title="AI investment thesis" actions={<Badge tone={thesis.fundamental_view === "BULLISH" ? "positive" : thesis.fundamental_view === "BEARISH" ? "negative" : "warning"}>{thesis.fundamental_view}</Badge>} /><div className="space-y-4 px-4 py-4"><div><p className="mb-1 text-2xs uppercase tracking-wider text-accent">AI ANALYSIS</p><p className="text-sm leading-7 text-foreground">{thesis.investment_thesis}</p></div><div className="grid gap-3 md:grid-cols-2"><TextBlock title="Bull case" text={assessmentSummary(thesis.catalysts.map((item) => item.description), "No catalysts returned by the research agent.")} /><TextBlock title="Bear case" text={thesis.bear_case || "No bear case returned by the research agent."} /></div><div><p className="mb-2 text-2xs uppercase tracking-wider text-muted">Confidence in research quality</p><div className="flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-elevated"><div className="h-1.5 rounded-full bg-accent" style={{ width: `${Math.max(0, Math.min(100, thesis.confidence * 100))}%` }} /></div><span className="font-mono text-xs text-foreground">{(thesis.confidence * 100).toFixed(0)}%</span></div><p className="mt-1 text-2xs text-subtle">Not a probability of return.</p></div><StatementsGrid assessments={[thesis.growth_assessment, thesis.profitability_assessment, thesis.cash_flow_assessment, thesis.balance_sheet_assessment, thesis.valuation_assessment]} /></div></Panel><MetadataPanel run={research.data!} /></div>
      <div className="grid gap-3 lg:grid-cols-2"><Panel><PanelHeader title="Key drivers and risks" /><div className="grid gap-4 p-4 md:grid-cols-2"><ListBlock title="Catalysts" items={thesis.catalysts.map((item) => item.description)} empty="No catalysts returned." /><ListBlock title="Risks" items={thesis.risks.map((item) => `[${item.severity}] ${item.description}`)} empty="No risks returned." /></div></Panel><Panel><PanelHeader title="Data quality" /><div className="divide-y divide-border/50">{thesis.data_quality.length ? thesis.data_quality.map((item) => <div key={item.area} className="flex items-center justify-between gap-3 px-4 py-2.5 text-xs"><span className="text-muted">{item.area}</span><span className="flex items-center gap-2"><DataQualityBadge state={item.quality} />{item.detail ? <span className="text-2xs text-subtle">{item.detail}</span> : null}</span></div>) : <EmptyState title="No research quality notes" description="The research output returned no additional data-quality annotations." />}</div>{thesis.limitations.length ? <p className="border-t border-border/50 px-4 py-2 text-2xs text-warning">Limitations: {thesis.limitations.join("; ")}</p> : null}</Panel></div>
      <Panel><PanelHeader title="Evidence workspace" actions={<span className="text-2xs text-subtle">SOURCE MATERIAL · not AI analysis</span>} />{evidenceItems.length ? <ul className="divide-y divide-border/50">{evidenceItems.map((item) => <EvidenceItem key={item.evidence_id} id={item.evidence_id} source={item.source} sourceType={item.source_type} claim={item.claim_supported} period={item.relevant_period} href={item.url} />)}</ul> : <EmptyState title="No evidence returned" description="The research run did not provide source references." />}</Panel>
      <div className="grid gap-3 xl:grid-cols-2"><Panel><PanelHeader title="Fundamentals" actions={<span className="text-2xs text-subtle">FACT · deterministic data · LLM never computes these</span>} /><FinancialTable metrics={fundamentals.data ?? []} loading={fundamentals.isLoading} error={fundamentals.isError} /></Panel><Panel><PanelHeader title="News and research documents" /><NewsAndDocuments news={snapshot.data?.news ?? []} documents={documents.data ?? []} loading={snapshot.isLoading || documents.isLoading} /></Panel></div>
      <div className="grid gap-3 xl:grid-cols-2"><GroundingPanel critic={critic} /><CriticPanel critic={critic} /></div>
      <Panel><PanelHeader title="Research event timeline" actions={<span className="text-2xs text-subtle">RUN {research.data?.id.slice(0, 8)}</span>} />{runEvents.length ? <EventTimeline events={runEvents} /> : <EmptyState title="No run-scoped events" description="Lifecycle events are available only when the backend correlates them to this run." />}</Panel>
      <Panel><PanelHeader title="Research run history" /><HistoryTable entries={history.data ?? []} loading={history.isLoading} /></Panel>
    </> : null}
  </div>;
}

function MarketValue({ label, value }: { label: string; value: string }) { return <div><p className="text-2xs uppercase tracking-wider text-subtle">{label}</p><p className="mt-1 font-mono text-sm text-foreground">{value}</p></div>; }

function TextBlock({ title, text }: { title: string; text: string }) { return <div><p className="text-2xs uppercase tracking-wider text-muted">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted">{text}</p></div>; }

function ListBlock({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <div><p className="text-2xs uppercase tracking-wider text-muted">{title}</p>{items.length ? <ul className="mt-2 list-inside list-disc space-y-1 text-xs text-muted">{items.map((item, i) => <li key={i}>{item}</li>)}</ul> : <p className="mt-2 text-xs text-subtle">{empty}</p>}</div>; }

function MetadataPanel({ run }: { run: import("@/lib/research-api").ResearchRun }) { const fields: [string, string | number | null | undefined][] = [["Provider", run.model_provider], ["Requested model", run.model_requested], ["Served model", run.model_name], ["Agent", run.agent_id], ["Agent version", run.agent_version], ["Prompt version", run.prompt_version], ["Context version", run.context_version], ["Context hash", null], ["Latency", run.latency_ms != null ? `${run.latency_ms} ms` : null], ["Input tokens", run.input_tokens], ["Output tokens", run.output_tokens], ["Total tokens", run.total_tokens], ["Cost", run.estimated_cost_usd != null ? `$${run.estimated_cost_usd}` : null]]; return <Panel><PanelHeader title="Research metadata" actions={<ModelBadge provider={run.model_provider} model={run.model_name} />} /><dl className="grid grid-cols-2 gap-x-4 gap-y-3 px-4 py-4 text-xs">{fields.map(([label, value]) => <div key={label}><dt className="text-2xs text-subtle">{label}</dt><dd className="mt-0.5 break-all font-mono text-foreground">{value ?? "—"}</dd></div>)}</dl><p className="border-t border-border/50 px-4 py-2 text-2xs text-warning">Context hash is not exposed by the current research API response.</p></Panel>; }

function StatementsGrid({ assessments }: { assessments: Assessment[] }) { return <div className="grid gap-x-4 gap-y-3 border-t border-border/50 pt-3 md:grid-cols-2">{assessments.map((assessment) => <div key={assessment.area}><p className="text-2xs uppercase tracking-wider text-muted">{assessment.area}</p><p className="mt-1 text-xs text-foreground">{assessment.summary}</p>{assessment.statements.map((statement, index) => <p key={index} className="mt-1 text-2xs text-muted"><span className={statement.kind === "FACT" ? "text-accent" : statement.kind === "INTERPRETATION" ? "text-warning" : "text-positive"}>{statement.kind}:</span> {statement.text}{statement.evidence_ids.length ? <span className="ml-1 font-mono text-subtle">[{statement.evidence_ids.join(", ")}]</span> : null}</p>)}</div>)}</div>; }

function GroundingPanel({ critic }: { critic: import("@/lib/research-api").CriticOutput | null }) { const checks = critic?.claim_checks ?? []; const unsupported = checks.filter((item) => item.status === "UNSUPPORTED").length; const contradicted = checks.filter((item) => item.status === "CONTRADICTED").length; return <Panel><PanelHeader title="Grounding" actions={<Badge tone={critic?.deterministic_checks_passed ? "positive" : critic ? "negative" : "neutral"}>{critic ? critic.deterministic_checks_passed ? "PASSED" : "FAILED" : "not connected"}</Badge>} />{critic ? <div className="grid grid-cols-3 gap-3 p-4"><Metric label="Checks" value={checks.length} /><Metric label="Unsupported" value={unsupported} tone={unsupported ? "negative" : undefined} /><Metric label="Contradicted" value={contradicted} tone={contradicted ? "negative" : undefined} /></div> : <EmptyState title="Grounding not yet available" description="A deterministic grounding result will appear after a completed research run." />}</Panel>; }

function CriticPanel({ critic }: { critic: import("@/lib/research-api").CriticOutput | null }) { return <Panel><PanelHeader title="Critic review" actions={critic ? <span className={`font-mono text-xs ${VERDICT_STYLES[critic.verdict]}`}>{critic.verdict}</span> : <Badge>not connected</Badge>} />{critic ? <div className="space-y-3 p-4">{critic.notes ? <p className="text-xs leading-relaxed text-muted">{critic.notes}</p> : null}{critic.findings.length ? <ul className="space-y-2">{critic.findings.map((finding, i) => <li key={i} className="text-xs"><span className="text-warning">[{finding.severity}]</span> <span className="text-subtle">{finding.category}:</span> <span className="text-muted">{finding.detail}</span></li>)}</ul> : <p className="text-xs text-muted">No critique findings returned.</p>}</div> : <EmptyState title="Critic not yet available" description="The critic has not returned a review for this research output." />}</Panel>; }

function Metric({ label, value, tone }: { label: string; value: string | number; tone?: "negative" }) { return <div className="border-l border-border pl-3"><p className="text-2xs text-subtle">{label}</p><p className={`mt-1 font-mono text-lg ${tone === "negative" ? "text-negative" : "text-foreground"}`}>{value}</p></div>; }

function FinancialTable({ metrics, loading, error }: { metrics: { metric: string; value: number | null; period_type: string; period_end: string; currency: string; quality: string }[]; loading: boolean; error: boolean }) { if (loading) return <LoadingState label="Loading deterministic fundamentals…" />; if (error) return <ErrorState description="Fundamentals could not be loaded." />; if (!metrics.length) return <EmptyState title="No financial data" description="Fundamental metrics are unavailable for this symbol." />; return <div className="overflow-x-auto"><table className="w-full min-w-[500px] text-xs"><tbody>{metrics.map((metric) => <tr key={`${metric.metric}-${metric.period_end}`} className="border-b border-border/40 last:border-0"><td className="px-4 py-2 text-muted">{METRIC_LABELS[metric.metric] ?? metric.metric}</td><td className="px-4 py-2 font-mono text-foreground">{formatMetric(metric.metric, metric.value, metric.currency)}</td><td className="px-4 py-2 text-2xs text-subtle">{metric.period_type} · {metric.period_end}</td><td className="px-4 py-2 text-right"><DataQualityBadge state={metric.quality} /></td></tr>)}</tbody></table></div>; }

function NewsAndDocuments({ news, documents, loading }: { news: { id?: string; headline: string; source: string | null; published_at: string }[]; documents: { document_id: string; title: string; document_type: string; source: string | null }[]; loading: boolean }) { if (loading) return <LoadingState label="Loading source material…" />; if (!news.length && !documents.length) return <EmptyState title="No news or documents" description="No source material was returned by the market and research APIs." />; return <div className="divide-y divide-border/50">{news.slice(0, 4).map((item, i) => <div key={item.id ?? i} className="px-4 py-3"><p className="text-xs text-foreground">{item.headline}</p><p className="mt-1 text-2xs text-subtle">NEWS · {item.source ?? "source unavailable"} · {new Date(item.published_at).toLocaleDateString()}</p></div>)}{documents.slice(0, 4).map((item) => <div key={item.document_id} className="px-4 py-3"><p className="text-xs text-foreground">{item.title}</p><p className="mt-1 text-2xs text-subtle">{item.document_type} · {item.source ?? "source unavailable"}</p></div>)}</div>; }

function EventTimeline({ events }: { events: import("@/lib/api").AgentEvent[] }) { return <ol className="divide-y divide-border/50">{events.map((event, index) => <li key={event.id} className="flex gap-3 px-4 py-3"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-accent/40 font-mono text-2xs text-accent">{index + 1}</span><div className="min-w-0"><p className="text-xs text-foreground">{event.event_type}</p><p className="mt-1 text-2xs text-muted">{event.agent_id} · {new Date(event.timestamp).toLocaleString()}</p></div></li>)}</ol>; }

function HistoryTable({ entries, loading }: { entries: { id: string; created_at: string; fundamental_view: string | null; confidence: number | null; critic_verdict: string | null; model_provider: string | null; model_name: string | null }[]; loading: boolean }) { if (loading) return <LoadingState label="Loading run history…" />; if (!entries.length) return <EmptyState title="No run history" description="Previous research runs will appear here when persisted by the backend." />; return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead><tr className="border-b border-border text-left text-2xs uppercase tracking-wider text-muted"><th className="px-3 py-2">Run</th><th className="px-3 py-2">Created</th><th className="px-3 py-2">View</th><th className="px-3 py-2">Confidence</th><th className="px-3 py-2">Critic</th><th className="px-3 py-2">Model</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-b border-border/40 last:border-0"><td className="px-3 py-2 font-mono text-accent">{entry.id.slice(0, 8)}</td><td className="px-3 py-2 text-muted">{new Date(entry.created_at).toLocaleString()}</td><td className={`px-3 py-2 ${entry.fundamental_view ? VIEW_STYLES[entry.fundamental_view] : "text-subtle"}`}>{entry.fundamental_view ?? "unavailable"}</td><td className="px-3 py-2 font-mono text-muted">{entry.confidence != null ? `${(entry.confidence * 100).toFixed(0)}%` : "unavailable"}</td><td className={`px-3 py-2 ${entry.critic_verdict ? VERDICT_STYLES[entry.critic_verdict] : "text-subtle"}`}>{entry.critic_verdict ?? "unavailable"}</td><td className="px-3 py-2 text-muted">{entry.model_provider && entry.model_name ? `${entry.model_provider} / ${entry.model_name}` : "unavailable"}</td></tr>)}</tbody></table></div>; }

function formatMetric(metric: string, value: number | null, currency: string) { if (value == null) return "unavailable"; if (metric.endsWith("_margin") || metric === "revenue_growth") return `${(value * 100).toFixed(1)}%`; const abs = Math.abs(value); const suffix = abs >= 1e9 ? "B" : abs >= 1e6 ? "M" : abs >= 1e3 ? "K" : ""; const divisor = suffix === "B" ? 1e9 : suffix === "M" ? 1e6 : suffix === "K" ? 1e3 : 1; return `${currency === "USD" ? "$" : ""}${(value / divisor).toFixed(2)}${suffix}`; }
function assessmentSummary(items: string[], empty: string) { return items.length ? items.join(" ") : empty; }
function asRecord(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" ? value as Record<string, unknown> : null; }
function numberValue(value: unknown): number | null { return typeof value === "number" && Number.isFinite(value) ? value : null; }
function overallQuality(items: { state: string }[] | undefined) { if (!items?.length) return "unavailable"; return items.some((item) => item.state === "invalid") ? "invalid" : items.some((item) => item.state === "missing") ? "missing" : items.some((item) => item.state === "stale") ? "stale" : "fresh"; }
function qualityLabel(items: { datatype: string; state: string }[] | undefined, datatype: string) { return items?.find((item) => item.datatype === datatype)?.state ?? "—"; }
