"use client";

import { useState } from "react";
import { Badge, EmptyState, Panel, PanelHeader, SectionHeader } from "@/components/ui";

type Tab = "registry" | "runs" | "comparison";
const TABS: { id: Tab; label: string }[] = [{ id: "registry", label: "Model registry" }, { id: "runs", label: "Evaluation runs" }, { id: "comparison", label: "Model comparison" }];

export default function ModelsPage() {
  const [tab, setTab] = useState<Tab>("registry");
  return <div className="space-y-5"><SectionHeader eyebrow="MODELS / EVALUATION CENTER" title="Model Lab" description="Compare provider-agnostic research models only when the backend has persisted comparable evaluation records." actions={<button disabled className="rounded border border-border px-3 py-2 text-xs text-subtle">Run evaluation · not connected</button>} /><Panel><div role="tablist" aria-label="Model lab views" className="flex gap-1 overflow-x-auto border-b border-border px-3 pt-2">{TABS.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)} className={`border-b-2 px-3 py-2 text-xs transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${tab === item.id ? "border-accent text-foreground" : "border-transparent text-muted hover:text-foreground"}`}>{item.label}</button>)}</div>{tab === "registry" ? <Registry /> : tab === "runs" ? <EvaluationRuns /> : <Comparison />}</Panel></div>;
}

function Registry() { return <div><PanelHeader title="Configured model architecture" actions={<Badge>availability unavailable</Badge>} /><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-xs"><thead><tr className="border-b border-border text-left text-2xs uppercase tracking-wider text-muted"><th className="px-3 py-2">Provider</th><th className="px-3 py-2">Model</th><th className="px-3 py-2">Served version</th><th className="px-3 py-2">Availability</th><th className="px-3 py-2">Last evaluation</th></tr></thead><tbody>{["OpenRouter", "Ollama", "Custom / self-hosted", "Direct providers"].map((provider) => <tr key={provider} className="border-b border-border/40 last:border-0"><td className="px-3 py-3 text-foreground">{provider}</td><td className="px-3 py-3 text-muted">unavailable</td><td className="px-3 py-3 font-mono text-muted">unavailable</td><td className="px-3 py-3"><Badge>not connected</Badge></td><td className="px-3 py-3 text-muted">unavailable</td></tr>)}</tbody></table></div><p className="border-t border-border/50 px-3 py-3 text-2xs text-subtle">Provider names reflect the existing model-gateway architecture. They are not claims that a provider is configured or reachable.</p></div>; }

function EvaluationRuns() { return <div><PanelHeader title="Evaluation run history" actions={<span className="text-2xs text-subtle">same-context comparisons</span>} /><EmptyState title="Evaluation API not yet exposed" description="The backend persists EvaluationRun records and lifecycle events, but no read route is currently registered. This table will populate once that contract is available." /><div className="border-t border-border/50 px-4 py-3"><dl className="grid gap-3 sm:grid-cols-4 text-xs"><Meta label="Run ID" /><Meta label="Symbol" /><Meta label="Context version" /><Meta label="Context hash" /></dl></div></div>; }

function Comparison() { const rows = ["Grounding", "Evidence coverage", "Latency", "Input tokens", "Output tokens", "Total tokens", "Estimated cost", "Critic verdict", "Structured output"]; return <div><PanelHeader title="Model comparison" actions={<Badge tone="warning">no benchmark data</Badge>} /><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead><tr className="border-b border-border text-left text-2xs uppercase tracking-wider text-muted"><th className="px-3 py-2">Metric</th><th className="px-3 py-2">Model A</th><th className="px-3 py-2">Model B</th><th className="px-3 py-2">Model C</th></tr></thead><tbody>{rows.map((row) => <tr key={row} className="border-b border-border/40 last:border-0"><td className="px-3 py-2 text-muted">{row}</td><td className="px-3 py-2 font-mono text-subtle">—</td><td className="px-3 py-2 font-mono text-subtle">—</td><td className="px-3 py-2 font-mono text-subtle">—</td></tr>)}</tbody></table></div><EmptyState title="Comparison unavailable" description="No model evaluation results are supplied by the current frontend API contract. Missing cost remains unavailable rather than zero." /></div>; }

function Meta({ label }: { label: string }) { return <div><dt className="text-2xs text-subtle">{label}</dt><dd className="mt-1 font-mono text-muted">unavailable</dd></div>; }
